name: MVVMCSwiftUI
options:
  settingPresets: project
attributes:
  LastSwiftUpdateCheck: "1520"
  BuildIndependentTargetsInParallel: "1"
  LastUpgradeCheck: "1520"
configs:
  Debug: debug
  Release: release
settings:
  base:
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    IPHONEOS_DEPLOYMENT_TARGET: "17.2"
    LOCALIZATION_PREFERS_STRING_CATALOGS: YES
    CLANG_CXX_LANGUAGE_STANDARD: "gnu++20"
    GCC_C_LANGUAGE_STANDARD: "gnu17"
  configs:
    Debug:
      GCC_PREPROCESSOR_DEFINITIONS: "DEBUG=1 $(inherited)"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG $(inherited)"
    Release:
      VALIDATE_PRODUCT: YES
      SWIFT_OPTIMIZATION_LEVEL: -O
targets:
  MVVMCSwiftUI:
    type: application
    platform: iOS
    sources: [MVVMCSwiftUI]
    attributes:
      CreatedOnToolsVersion: "15.2"
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "AccentColor"
        CLANG_CXX_LIBRARY: "libc++"
        CODE_SIGN_STYLE: "Automatic"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_ASSET_PATHS: "\"MVVMCSwiftUI/Preview Content\""
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        LD_RUNPATH_SEARCH_PATHS: ["$(inherited)", "@executable_path/Frameworks"]
        MARKETING_VERSION: "1.0"
        PRODUCT_BUNDLE_IDENTIFIER: "br.com.rbailoni.MVVMCSwiftUI"
        PRODUCT_NAME: $(TARGET_NAME)
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        
        
        
        
        
        
        
        
        
        
        
        
#          ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
#          CLANG_CXX_LIBRARY: libc++
#          CODE_SIGN_STYLE: Automatic
#          CURRENT_PROJECT_VERSION: 1
#          DEVELOPMENT_ASSET_PATHS: "NavigationStackTest/Preview Content"
#          ENABLE_PREVIEWS: YES
#          GENERATE_INFOPLIST_FILE: YES
#          INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
#          INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
#          INFOPLIST_KEY_UILaunchScreen_Generation: YES
#          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad = UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
#          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone = UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
#          MARKETING_VERSION = 1.0
#          PRODUCT_BUNDLE_IDENTIFIER = br.com.rbailoni.NavigationStackTest
#          PRODUCT_NAME = $(TARGET_NAME)
#          SWIFT_EMIT_LOC_STRINGS = YES
#          SWIFT_VERSION = 5.0
